# DAG execution strategy: choose how the pipeline runs (work_queue, level, reactive, hybrid)
strategy: work_queue

# Processor definitions: each processor declares its type, config, and dependencies
processors:
  - id: caser
    type: local
    impl: Caser

  - id: token-counter
    type: grpc
    endpoint: https://auth-service:50051
    depends_on: [ capitalizer]

  - id: character-
    type: local
    impl: MetricsCollector
    depends_on: [logger]

  - id: audit
    type: grpc
    endpoint: https://audit-service:50052
    depends_on: [auth, metrics]

  - id: sanitizer
    type: wasm
    module: ./plugins/sanitize.wasm
    depends_on: [auth]