strategy: reactive
failure_strategy: fail_fast
executor_options:
  max_concurrency: 2

processors:
  - id: rle_rust
    type: wasm
    module: /data/development/projects/the-dagwood/wasm_components/rle_rust.wasm
    depends_on: []
