strategy: reactive
failure_strategy: fail_fast
executor_options:
  max_concurrency: 2

processors:
  - id: run_length_encoder
    type: wasm
    module: wasm_components/rle_assemblyscript.wasm
    depends_on:
    options:
      intent: analyze
